# Generated by Django 5.2.5 on 2025-08-19 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemate_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 19, 15, 57, 15, 11033, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
