# Generated by Django 5.2.5 on 2025-08-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemate_app', '0003_streamplatform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='moviemate_app.streamplatform'),
            preserve_default=False,
        ),
    ]
