# Generated by Django 5.2.5 on 2025-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemate_app', '0006_reveiw_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
